version: '3.9'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: Api
    environment:
      USE_DOCKER: "true"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - backend
    depends_on:
      - db

  db:
    container_name: FastApiDb
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    networks:
      - backend

  minio:
    image: bitnami/minio:2024.11.7
    restart: always
    ports:
      - "9000:9000"
      - "7000:7000"
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "veryhardpassword"
      MINIO_DEFAULT_BUCKETS: "main"
      MINIO_API_PORT_NUMBER: "9000"
      MINIO_CONSOLE_PORT_NUMBER: "7000"
    volumes:
      - minio-data:/bitnami/minio/data

  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db-data:
  minio-data: